language: python

python:
  - 2.7
  - 3.5

env:
  matrix:
  - DJANGO='django18' CMS='cms33'
  - DJANGO='django19' CMS='cms33'

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"

script:
  - tox -e"$PYVER-$DJANGO-$CMS"
